### ISSUE TITLE
Add messages

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#837] opened 2017-08-24 08:25 UTC
#### Issue description
 Invalid name! Message not sending and server closed message not to send

#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by armagadon159753** [comment] 2017-08-24 08:26
Wath did  you do?

**Comment by SuperAdam47** [comment] 2017-08-24 08:27
Nothing

**Comment by erkam2002** [comment] 2017-08-24 09:32
lol

**Comment by MasterOfTheRealm** [comment] 2017-08-24 13:54
Duplicate of #604

**Closed** 2017-08-24 22:02 UTC
