### ISSUE TITLE
Server Crashes by starting.

### ISSUE THREAD

**Issue by OfficialAndii** [GenisysPro/GenisysPro#840] opened 2017-08-24 16:28 UTC
Server OS:
Ubuntu 16.02
Genyisys Version: Newest

Server Log by starting:
2017-08-24 [18:22:12] [Server thread/WARNING]: OpenSSL extension not found
2017-08-24 [18:22:12] [Server thread/WARNING]: Please configure OpenSSL extension for PHP if you want to use Xbox Live authentication or global resource pack.
2017-08-24 [18:22:12] [Server thread/INFO]: Selected English (eng) as the base language
2017-08-24 [18:22:12] [Server thread/WARNING]: Debugging assertions are enabled, this may impact on performance. To disable them, set `zend.assertions = -1` in php.ini.
2017-08-24 [18:22:12] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\Server::get_calling_class() must be of the type string, null returned" (EXCEPTION) in "/src/pocketmine/Server" at line 339
2017-08-24 [18:22:12] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2017-08-24 [18:22:12] [Server thread/EMERGENCY]: Please upload the "/home/mcpe/mcpe/crashdumps/CrashDump_Thu_Aug_24-18.22.12-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2017-08-24 [18:22:12] [Server thread/CRITICAL]: Error: "Call to a member function disablePlugins() on null" (EXCEPTION) in "/src/pocketmine/Server" at line 2358

**Comment by Leo3418** [comment] 2017-08-24 21:57
Duplicate of #839 
Before you submit any issue, please have a look at all other existing issues, and make sure your issue does not duplicate any other issue. Thank you!

**Closed by Leo3418** 2017-08-24 21:57 UTC
Labels: Duplicate, Invalid
