### ISSUE TITLE
Chunks not Loading....

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#641] opened 2017-07-28 11:44 UTC
**Bug:**
When I teleporting to a world the Chunks not loading....

**Comment by Leo3418** [comment] 2017-07-28 12:21
Duplicate of #623 
Before you submit any issue, please have a look at all other existing issue, and make sure this issue does not duplicate any other issue. Thank you!

**Closed by Leo3418** 2017-07-28 12:21 UTC
Labels: Duplicate

**Comment by BexiPE** [comment] 2017-07-28 12:26
wow, but it isnt fix...

**Comment by Leo3418** [comment] 2017-07-28 12:38
We're aware of this issue. If you want to report more information about this issue, please post it in #623. Please do not open another issue reporting the same problem.
