### ISSUE TITLE
打开物品栏闪退

### ISSUE THREAD

**Issue by huaji2333** [GenisysPro/GenisysPro#108] opened 2017-06-08 00:08 UTC
一打开物品栏就闪退
mcpe1.1.0.55
geinsys 1.1dev

**Comment by huaji2333** [comment] 2017-06-08 00:09
bug

**Comment by DerddyDert** [comment] 2017-06-08 00:09
Can't you tanslate to English please?

**Comment by DerddyDert** [comment] 2017-06-08 01:27
Thanks! This is a duplicate of #107 (if I translated correctly) Please re-open if different.

**Closed by DerddyDert** 2017-06-08 01:27 UTC
Labels: bug, duplicate
