### ISSUE TITLE
[RESOLVED] Server crashes on Rpi 3 32 bit

### ISSUE THREAD

**Issue by Borduni** [GenisysPro/GenisysPro#332] opened 2017-07-07 06:02 UTC
#### Issue description
Every time i join on my server, i get this error, and then the server crashes
 [07:56:05] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\AddPlayerPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[07:56:05] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[07:56:05] [Server thread/EMERGENCY]: Please upload the "/home/pi/pm/crashdumps/CrashDump_Fri_Jul_7-07.56.05-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

#### Steps to reproduce the issue
I dont know. Install slapper, join and let the server crash

#### OS and versions

* Genisys: newest build since ive updated deu.ini
* PHP: 7.0.6
* Server OS: Raspbian OS 32bit
* Game version: 1.1.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

GenisysPro Crash Dump Fri Jul 7 07:56:05 CEST 2017

Error: Class pocketmine\network\mcpe\protocol\AddPlayerPacket not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 			if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 				$name::onClassLoaded();
[138] 			}
[139] 			
[140] 			$this->classes[] = $name;
[141] 
[142] 			return true;
[143] 		}elseif($this->getParent() === null){
[144] 			throw new ClassNotFoundException("Class $name not found");
[145] 		}
[146] 
[147] 		return false;
[148] 	}
[149] 
[150] 	/**
[151] 	 * Returns the path for the class, if any
[152] 	 *
[153] 	 * @param string $name
[154] 	 *

Backtrace:
#0 /Slapper/src/slapper/entities/SlapperHuman(65): spl_autoload_call(string pocketmine\network\mcpe\protocol\AddPlayerPacket)
#1 /src/pocketmine/Player(958): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player Player(1))
#2 /src/pocketmine/Player(918): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1907): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2729): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2446): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2324): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1922): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(470): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/pi/pm/PocketMine-MP.phar/, string /home/pi/pm/, string /home/pi/pm/plugins/)
#9 (1): require_once(string phar:///home/pi/pm/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l
PHP version: 7.0.6
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 45 seconds
Number of loaded worlds: 2
Players online: 1/40

Loaded plugins:
MagicWE 0.2.4 by thebigsmileXD for API(s) 1.13.0, 2.0.0
TheFloorIsLava 1 by StuckDexter for API(s) 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
SlapperRotation 1.0.1 by jojoe77777 for API(s) 2.0.0
EasyNick 1.0.0 by Bluplayz for API(s) 1.0.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
Lobby 1 by UltimateDevs for API(s) 2.0.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
WearArmorFast 1.0.0 by khavmc for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
DevTools 1.11.3 by PocketMine Team for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
SlapperCache 1.0.1 by jojoe77777 for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6
Slapper 1.3.5 by jojoe77777 for API(s) 3.0.0-ALPHA5, 3.0.0-ALPHA6
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by SuperKali** [comment] 2017-07-07 06:04
Remove the all Plugin!
@Borduni  This error is caused by a plugin

**Comment by SuperKali** [comment] 2017-07-07 06:05
@Borduni remove the Plugin slapper and slappercache and slapperrotation

**Comment by Borduni** [comment] 2017-07-07 06:06
Yea, I know, but I need these plugins...

**Comment by Borduni** [comment] 2017-07-07 06:06
Is there any alternative?

**Comment by SuperKali** [comment] 2017-07-07 06:07
Moment Now I'm sending you a slapper

**Comment by SuperKali** [comment] 2017-07-07 06:07
@Borduni remove slappercache

**Comment by Borduni** [comment] 2017-07-07 06:08
per mail?

**Comment by SuperKali** [comment] 2017-07-07 06:09
Nope per github

**Comment by Borduni** [comment] 2017-07-07 06:10
Okay, link?

**Comment by SuperKali** [comment] 2017-07-07 06:11
@Borduni [Slapper-Compatible_GenisysPro.zip](https://github.com/GenisysPro/GenisysPro/files/1130148/Slapper-Compatible_GenisysPro.zip)

**Comment by SuperKali** [comment] 2017-07-07 06:12
@Borduni Please close this poll and test it

**Comment by Borduni** [comment] 2017-07-07 06:12
Thanks :)

**Comment by Borduni** [comment] 2017-07-07 06:13
`wget https://github.com/GenisysPro/GenisysPro/files/1130148/Slapper-Compatible_GenisysPro.zip`
`unzip Slapper-Compatible_GenisysPro.zip`

**Comment by SuperKali** [comment] 2017-07-07 06:15
@DerddyDert Close this issue was just a stupid plugin that crashed

**Comment by Borduni** [comment] 2017-07-07 06:16
Works now

**Comment by Borduni** [comment] 2017-07-07 06:16
Thnx

**Comment by SuperKali** [comment] 2017-07-07 06:17
@Borduni ok close this issue !

**Closed** 2017-07-07 06:17 UTC
