### ISSUE TITLE
Help me with this bug

### ISSUE THREAD

**Issue by alair069** [GenisysPro/GenisysPro#306] opened 2017-07-04 00:57 UTC
![-c1govyy](https://user-images.githubusercontent.com/27539870/27811244-9756f188-603a-11e7-8dd5-e2dce93cfe36.jpg)

**Comment by DerddyDert** [comment] 2017-07-04 01:13
Need more info. What plugins you using? What are you doing that causes this?

**Comment by alair069** [comment] 2017-07-04 01:16
My server is skywars, Alas this happens, Chests do not open, Chests are fading ....

**Comment by CookieCode** [comment] 2017-07-04 01:17
Templo, Is a mca world, mcr ... ?

**Comment by alair069** [comment] 2017-07-04 01:18
mca

**Comment by CookieCode** [comment] 2017-07-04 02:50
Lol read my question -_-...

**Comment by alair069** [comment] 2017-07-04 03:41
MCA

**Comment by MasterOfTheRealm** [comment] 2017-07-05 16:11
@alair069 Chests do not open - maybe because of your spawn protection

**Comment by alair069** [comment] 2017-07-05 18:42
I do not have protection plugin for the other worlds, just for the lobby

**Comment by DerddyDert** [comment] 2017-07-05 20:21
#317 Same?

**Comment by DerddyDert** [comment] 2017-07-05 22:05
There have been some updates but I think the issue is here https://github.com/GenisysPro/GenisysPro/commit/bfec0eabb662ed777d4906a965f7cfbc1394a82a 	bfec0ea

**Comment by DerddyDert** [comment] 2017-07-12 01:00
I'm closing this. Reopen if you can recreate

**Closed by DerddyDert** 2017-07-12 01:00 UTC
Labels: Unconfirmed
